
export const imagenes = {
  Autorito: {
    "1": "/Imagenes/Autorito/1.webp",
    "2": "/Imagenes/Autorito/2.webp",
    "3": "/Imagenes/Autorito/3.png",
    "4": "/Imagenes/Autorito/4.webp",
    "5": "/Imagenes/Autorito/5.webp",
  },
  ToDo: {
    "1": "/Imagenes/ToDo/1.webp",
    "2": "/Imagenes/ToDo/2.jpg",
  },
  WhatsApp: {
    "1": "/Imagenes/Whatsapp/1.webp",
    "2": "/Imagenes/Whatsapp/2.jpg",
  },
  Uturi: {
    "1": "/Imagenes/Uturi/1.webp",
    "2": "/Imagenes/Uturi/2.webp",
    "3": "/Imagenes/Uturi/3.webp",
    "4": "/Imagenes/Uturi/4.webp",
    "5": "/Imagenes/Uturi/5.webp",
    "6": "/Imagenes/Uturi/6.webp",
    "7": "/Imagenes/Uturi/7.webp",
    "8": "/Imagenes/Uturi/8.webp",
    "9": "/Imagenes/Uturi/9.webp",
    "10": "/Imagenes/Uturi/10.webp",
    "11": "/Imagenes/Uturi/11.webp",
    "12": "/Imagenes/Uturi/12.webp",
    "13": "/Imagenes/Uturi/13.webp",
    "14": "/Imagenes/Uturi/14.webp",
    "15": "/Imagenes/Uturi/15.webp",
    "16": "/Imagenes/Uturi/16.webp",
    "17": "/Imagenes/Uturi/17.webp",
    "18": "/Imagenes/Uturi/18.webp",
  },
  Melomix: {
    "1": "/Imagenes/Melomix/1.webp",
    "2": "/Imagenes/Melomix/2.webp",
    "3": "/Imagenes/Melomix/3.webp",
    "4": "/Imagenes/Melomix/4.webp",
    "5": "/Imagenes/Melomix/5.webp",
    "6": "/Imagenes/Melomix/6.webp",
    "7": "/Imagenes/Melomix/7.webp",
    "8": "/Imagenes/Melomix/8.webp",
    "9": "/Imagenes/Melomix/9.webp",
    "10": "/Imagenes/Melomix/10.webp",
    "11": "/Imagenes/Melomix/11.webp",
    "12": "/Imagenes/Melomix/12.webp",
    "13": "/Imagenes/Melomix/13.webp",
    "14": "/Imagenes/Melomix/14.webp",
    "15": "/Imagenes/Melomix/15.webp",
    "16": "/Imagenes/Melomix/16.webp",
    "17": "/Imagenes/Melomix/17.webp",
    "18": "/Imagenes/Melomix/18.webp",
    "19": "/Imagenes/Melomix/19.webp",
    "20": "/Imagenes/Melomix/20.webp",
    "21": "/Imagenes/Melomix/21.webp",
    "22": "/Imagenes/Melomix/22.webp",
    "23": "/Imagenes/Melomix/23.webp",
    "24": "/Imagenes/Melomix/24.webp"
  },
  ProjectManager: {
    "1": "/Imagenes/ProyectManager/1.webp",
    "2": "/Imagenes/ProyectManager/2.webp",
    "3": "/Imagenes/ProyectManager/3.webp",
    "4": "/Imagenes/ProyectManager/4.webp",
    "5": "/Imagenes/ProyectManager/5.webp",
    "6": "/Imagenes/ProyectManager/6.webp",
    "7": "/Imagenes/ProyectManager/7.webp",
    "8": "/Imagenes/ProyectManager/8.webp",
    "9": "/Imagenes/ProyectManager/9.webp",
    "10": "/Imagenes/ProyectManager/10.webp",
    "11": "/Imagenes/ProyectManager/11.webp",
    "12": "/Imagenes/ProyectManager/12.webp",
  }
}