export const textosPorIdioma = {
  es: {
    h1: "Alonso Roano, Desarrollador Frontend",
    titulo: "Alonso Roano",
    subtitulo: "Desarrollador/Estudiante",
    inicio: "<Inicio/>",
    sobreMi: "<Sobre mí/>",
    conocimientos: "<Conocimientos/>",
    proyectos: "<Proyectos/>",
    copiarCorreo: "Correo copiado al portapapeles.",
    copiarTelefono: "Teléfono copiado al portapapeles.",
    lema: "Mi lema es: \"Es difícil decir que algo es imposible, porque el sueño de ayer es la esperanza de hoy y la realidad de mañana\" - Robert H. Goddard",
    textoConocimientos: "Estas son las tecnologías en las que tengo conocimiento.",
    frontendTitulo: "Frontend",
    frontend: "HTML, CSS, y JS. Con el uso de los frameworks React, Vite y Tailwind.",
    backendTitulo: "Backend",
    backend: "Node.js, Express, Python, PHP y SQL.",
    diseñoTitulo: "Diseño",
    descripcion: "Me considero una persona centrada en el cumplimiento de objetivos. Cuando se me encomienda un trabajo, trato de resolverlo utilizando las habilidades que poseo en ese momento y, si es necesario, aprendo nuevas habilidades. Sé manejar el estrés de manera efectiva y mantener mi concentración en un objetivo sin desviarme del camino.",
    diseño: "Adobe, Photoshop y Figma.",
    flujoTrabajoTitulo: "Flujo de trabajo",
    flujoTrabajo: " Git, GitHub, Star UML y Microsoft Office.",
    saludoInicial: "Entusiasta por el desarrollo web, Cancún, Quintana Roo, México.",
    proyectosTitulo: "<Proyectos/>",
    proyectosTexto: "Estos son mis proyectos concluidos.",
    Autorito: "Un sitio web programado en PHP sobre gestión de autos, utilizando los servicios de Apache.",
    ToDo: "Una aplicación de gestión de tareas programada en el framework React Native, diseñada tanto para Android como para web.",
    WhatsApp: "Una réplica de la aplicación WhatsApp programada en el framework Flet.",
    Uturi: "Una aplicación web programada en React que se encarga de la administración y recomendación de sitios turísticos en Cancún, Quintana Roo.",
    Melomix: "Una aplicación web programada en Vite con Tailwind que se encarga de la administración y recomendación de artistas y canciones varias.",
    ProjectManager: "Una aplicación web programada en React que se encarga de la administración de distintos proyectos del usuario.",
  },
  en: {
    h1: "Alonso Roano, Frontend Developer",
    titulo: "Alonso Roano",
    subtitulo: "Developer / Student",
    inicio: "<Home/>",
    sobreMi: "<About Me/>",
    conocimientos: "<Skills/>",
    proyectos: "<Projects/>",
    descripcion: "I consider myself a person focused on meeting objectives. When I am given a job, I try to solve it using the skills I possess at that moment and, if necessary, learn new skills. I know how to manage stress effectively and maintain my concentration on a goal without deviating from the path.",
    copiarCorreo: "Email copied to clipboard.",
    copiarTelefono: "Phone copied to clipboard.",
    lema: "My motto is: \"It's difficult to say that something is impossible, because the dream of yesterday is the hope of today and tomorrow's reality\" - Robert H. Goddard",
    textoConocimientos: "These are the technologies I have knowledge of.",
    frontendTitulo: "Frontend",
    frontend: "HTML, CSS, and JS. Using frameworks like React, Vite, and Tailwind.",
    backendTitulo: "Backend",
    backend: "Node.js, Express, Python, PHP, and SQL.",
    diseñoTitulo: "Design",
    diseño: "Adobe, Photoshop, and Figma.",
    flujoTrabajoTitulo: "Workflow",
    flujoTrabajo: "Git, GitHub, Star UML and Microsoft Office.",
    saludoInicial: "Enthusiastic about web development, Cancún, Quintana Roo, México.",
    proyectosTitulo: "<Projects/>",
    proyectosTexto: "These are my completed projects.",
    Autorito: "A PHP-based website about car management, utilizing Apache services.",
    ToDo: "A task management application programmed in React Native framework, designed for both Android and Web.",
    WhatsApp: "A replica of the WhatsApp application programmed in the Flet framework.",
    Uturi: "A web application programmed in React that manages and recommends tourist sites in Cancun, Quintana Roo.",
    Melomix: "A web application programmed in Vite with Tailwind that manages and recommends various artists and songs.",
    ProjectManager: "A web application programmed in React that manages different user projects.",
  },
};